baseURL: https://eyeofparadox.github.io/
# https://hbs-skeleton.netlify.app/
title: eyeofparadox on github
copyright: 'Copyright Â© 2007-2025 eyeofparadox. All Rights Reserved.'
defaultContentLanguage: en
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  # news: /news/:year/:month/:title/
  posts: /posts/:year/:month/:title/
  pages: /pages/:year/:month/:title/

module:
  imports:
    - path: github.com/eyeofparadox/hugo-theme-bootstrap
#   proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
